/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0nElvUnuKGP
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
    TableHead,
    TableRow,
    TableHeader,
    TableCell,
    TableBody,
    Table
} from '@/components/ui/table'

export function EventInfo() {
    return (
        <div className="mx-auto my-8 max-w-4xl">
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead className="md rounded-bl-md rounded-tl-md bg-brand-500 text-white">
                            Description
                        </TableHead>
                        <TableHead className="rounded-br-md rounded-tr-md bg-brand-500 text-white">
                            Time / Details
                        </TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    <TableRow>
                        <TableCell>Doors open to attendees</TableCell>
                        <TableCell className="font-mono">09:00 AM</TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Educational Sessions I</TableCell>
                        <TableCell className="font-mono">
                            <div>10:00 AM - Welcome, Markus Arnold (WMC)</div>
                            <div>
                                10:05 AM - 10:25 AM: Live-Demo BMF, Stefan Münz
                                (WAFIOS AG)
                            </div>
                            <div>
                                10:30 AM - 11:00 AM: Keynote speech, David
                                Fulton (BorgWarner)
                            </div>
                            <div>
                                11:00 AM - 11:30 AM: Technology Presentation,
                                Tobias Single (WAFIOS AG)
                            </div>
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Networking/machine demos</TableCell>
                        <TableCell className="font-mono">
                            11:30 AM - 12:00 PM
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Lunch</TableCell>
                        <TableCell className="font-mono">
                            12:00 PM - 01:00 PM
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Networking/machine demos</TableCell>
                        <TableCell className="font-mono">
                            01:00 PM - 01:30 PM
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Educational Sessions II</TableCell>
                        <TableCell className="font-mono">
                            <div>
                                01:30 PM - 01:50 PM: Technology Presentation,
                                Marcell Wardin (Gehring)
                            </div>
                            <div>01:50 PM - 03:00 PM: Vendor presentations</div>
                            <div>
                                Trumpf • HPW • DuPont • Brockhaus • Zeiss •
                                Schuler
                            </div>
                            <div>Balance Systems • Witels-Albert • Streck</div>
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Networking/machine demos</TableCell>
                        <TableCell className="font-mono">
                            03:00 PM - 05:00 PM
                        </TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>End of show</TableCell>
                        <TableCell className="font-mono">05:00 PM</TableCell>
                    </TableRow>
                </TableBody>
            </Table>
        </div>
    )
}
